/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Tela;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import manipular.IAluno;
import modelo.Aluno;
import persistencia.DadosArqui;

public class TelaInicio extends javax.swing.JFrame {    
    
    IAluno alunos = null;
    public TelaInicio() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        Ordenar.setModel(new javax.swing.DefaultComboBoxModel(ORDENACAO.values()));
        Tabela.setEnabled(false);
        Buscar.setEnabled(false);
        Incluir.setEnabled(false);
        Listar.setEnabled(false);
        Ordenar.setEnabled(false);
        
        ajustarTamanhoColunas();
    }
            
    public enum ORDENACAO {
    crescente_nome,
    decrescente_nome,
    crescente_matricula,
    decrescente_matricula,
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        Incluir = new javax.swing.JButton();
        Ordenar = new javax.swing.JComboBox<>();
        Buscar = new javax.swing.JButton();
        Listar = new javax.swing.JButton();
        Carregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Lista de alunos ultilizando arvore binaria");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Matricula ", "Nome", "Turno", "Periodo", "Enfase", "Curso"
            }
        ));
        Tabela.setToolTipText("");
        Tabela.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Tabela.setName(""); // NOI18N
        Tabela.setShowGrid(false);
        jScrollPane1.setViewportView(Tabela);

        Incluir.setText("Incluir");
        Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncluirActionPerformed(evt);
            }
        });

        Ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "crescente-nome", "decrecente-nome", "crecente-matricula", "decrecente-matricula", " " }));

        Buscar.setText("Buscar");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Listar.setText("Relistar ");
        Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarActionPerformed(evt);
            }
        });

        Carregar.setText("Carregar ");
        Carregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1077, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Incluir)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Carregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carregar)
                    .addComponent(Incluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Listar)
                    .addComponent(Buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        try {
        TelaBuscar telabuscar = new TelaBuscar(this,true);
        telabuscar.setLocationRelativeTo(null);
        telabuscar.setVisible(true);
        Aluno novo = new Aluno();
        String[] infBusca = new String[2];
        List<Aluno> resultadoBusca = null;
        infBusca = telabuscar.exportarDadosBusca(infBusca);
        if(infBusca != null){
        resultadoBusca = alunos.buscar(infBusca[0], infBusca[1]);
        telabuscar.receberResultadoBusca(resultadoBusca);
        telabuscar.dispose();
        }
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage() + "Incluir buscar\n");
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncluirActionPerformed
       try {
        Aluno novo = new Aluno();
        TelaIncluir telaincluir = new TelaIncluir(this,true);
        telaincluir.setLocationRelativeTo(null);
        telaincluir.setVisible(true);
        novo = telaincluir.exportarDadosCadastro(novo);
        if(novo != null){
        alunos.incluir(novo);
        }
        Buscar.setEnabled(true);
        Incluir.setEnabled(true);
        Listar.setEnabled(true);
        Ordenar.setEnabled(true);
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage() + "Incluir Dados\n");
        }
    }//GEN-LAST:event_IncluirActionPerformed

    private void CarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarregarActionPerformed
        try { 
        JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("text","csv");
        fc.setFileFilter(filtro);
        int res = fc.showOpenDialog(null);
        if (res == JFileChooser.APPROVE_OPTION) {
            File arquivo = fc.getSelectedFile();
            DadosArqui dados = new DadosArqui(arquivo);
            alunos = dados.obterAlunos();
            
            Incluir.setEnabled(true);
            Buscar.setEnabled(true);
            Listar.setEnabled(true);
            Ordenar.setEnabled(true);
            
            ListarActionPerformed(evt);
        }
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage() + "Carregar Dados\n");
        } 
    }//GEN-LAST:event_CarregarActionPerformed

    private void ajustarTamanhoColunas() {
    Tabela.getColumnModel().getColumn(0).setMinWidth(120);       // 1
    Tabela.getColumnModel().getColumn(0).setMaxWidth(120);       // matricula
    Tabela.getColumnModel().getColumn(1).setMinWidth(300);       // 1
    Tabela.getColumnModel().getColumn(1).setPreferredWidth(400); // Nome
    Tabela.getColumnModel().getColumn(1).setMaxWidth(2000);      // 1
    Tabela.getColumnModel().getColumn(2).setMinWidth(120);       // turno
    Tabela.getColumnModel().getColumn(2).setMaxWidth(120);       // 2
    Tabela.getColumnModel().getColumn(3).setMinWidth(80);        // periodo
    Tabela.getColumnModel().getColumn(3).setMaxWidth(80);        // 3
    Tabela.getColumnModel().getColumn(4).setMinWidth(140);       // Ênfase
    Tabela.getColumnModel().getColumn(4).setMaxWidth(280);       // 4
    Tabela.getColumnModel().getColumn(5).setMinWidth(200);       // curso
    Tabela.getColumnModel().getColumn(5).setMaxWidth(400);       // 5
}
    
    private void ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarActionPerformed
       try {
        List<Aluno> array = alunos.listar(Ordenar.getSelectedItem().toString());
        Tabela.setRowHeight(30);
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {},
        new String [] {"Matricula", "Nome", "Turno", "Periodo","Enfase","Curso"}
        ));
        
        ajustarTamanhoColunas();
        
        DefaultTableModel model = (DefaultTableModel) Tabela.getModel();
        for(int j = 0; j<6;j++){
            Tabela.getColumnModel().getColumn(j).setCellRenderer(new MultiLineTableCellRenderer());
        }
        model.setNumRows(0);
        String[] saida = new String[6];
        int size;
        size = array.size();
        for(int i = 0;i < size; i++){
            saida[0] = array.get(i).getMatricula() + "";
            saida[1] = array.get(i).getNome() + "";
            saida[2] = array.get(i).getTurno() + "";
            saida[3] = array.get(i).getPeriodo() + "";
            saida[4] = array.get(i).getEnfase() + "";
            saida[5] = array.get(i).getCurso() + "";
            model.addRow(saida);
        }
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage() + "Listar Dados\n");
        }
    }//GEN-LAST:event_ListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Carregar;
    private javax.swing.JButton Incluir;
    private javax.swing.JButton Listar;
    private javax.swing.JComboBox<String> Ordenar;
    private javax.swing.JTable Tabela;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
