/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

public class TelaInicial extends javax.swing.JFrame {

  /**
   * Creates new form TelaPrincipal
   */
  public TelaInicial() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Veiculo = new javax.swing.JButton();
        Acessorio = new javax.swing.JButton();
        Posse = new javax.swing.JButton();
        Marcas = new javax.swing.JButton();
        Modelos = new javax.swing.JButton();
        Cliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("GASTOS VEICULARES");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("SISTEMA DE CONTROLE");

        Veiculo.setBackground(new java.awt.Color(204, 204, 204));
        Veiculo.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        Veiculo.setForeground(new java.awt.Color(255, 255, 255));
        Veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/seguro-de-automovel.png"))); // NOI18N
        Veiculo.setText("VEÍCULOS");
        Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VeiculoActionPerformed(evt);
            }
        });

        Acessorio.setBackground(new java.awt.Color(204, 204, 204));
        Acessorio.setFont(new java.awt.Font("Helvetica Neue", 3, 30)); // NOI18N
        Acessorio.setForeground(new java.awt.Color(255, 255, 255));
        Acessorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/cabo-usb.png"))); // NOI18N
        Acessorio.setText("ACESSÓRIO");
        Acessorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcessorioActionPerformed(evt);
            }
        });

        Posse.setBackground(new java.awt.Color(204, 204, 204));
        Posse.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        Posse.setForeground(new java.awt.Color(255, 255, 255));
        Posse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/grupo.png"))); // NOI18N
        Posse.setText("POSSE");
        Posse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosseActionPerformed(evt);
            }
        });

        Marcas.setBackground(new java.awt.Color(204, 204, 204));
        Marcas.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        Marcas.setForeground(new java.awt.Color(255, 255, 255));
        Marcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/seguro-de-automovel.png"))); // NOI18N
        Marcas.setText("MARCAS");
        Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcasActionPerformed(evt);
            }
        });

        Modelos.setBackground(new java.awt.Color(204, 204, 204));
        Modelos.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        Modelos.setForeground(new java.awt.Color(255, 255, 255));
        Modelos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/engarrafamento.png"))); // NOI18N
        Modelos.setText("MODELOS");
        Modelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModelosActionPerformed(evt);
            }
        });

        Cliente.setBackground(new java.awt.Color(204, 204, 204));
        Cliente.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
        Cliente.setForeground(new java.awt.Color(255, 255, 255));
        Cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/grupo.png"))); // NOI18N
        Cliente.setText("CLIENTE");
        Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Acessorio, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modelos, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(Posse, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Marcas, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2))
                .addGap(188, 188, 188))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Veiculo)
                    .addComponent(Posse))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Marcas)
                    .addComponent(Acessorio))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Cliente)
                    .addComponent(Modelos))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VeiculoActionPerformed
    // TODO add your handling code here:
    telaVeiculo janelaVeic = new telaVeiculo();
    janelaVeic.setVisible(true);
  }//GEN-LAST:event_VeiculoActionPerformed

    private void AcessorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcessorioActionPerformed
        // TODO add your handling code here:
        telaAcessorio janelaAcessorio = new telaAcessorio();
        janelaAcessorio.setVisible(true);
    }//GEN-LAST:event_AcessorioActionPerformed

    private void PosseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosseActionPerformed
        // TODO add your handling code here:
        telaPosse TelaPosse = new telaPosse();
        TelaPosse.setVisible(true);
    }//GEN-LAST:event_PosseActionPerformed

    private void MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcasActionPerformed
        // TODO add your handling code here:
        telaMarca TelaMarca = new telaMarca();
        TelaMarca.setVisible(true);
    }//GEN-LAST:event_MarcasActionPerformed

    private void ModelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModelosActionPerformed
        // TODO add your handling code here:
        telaModelo TelaModelo = new telaModelo();
        TelaModelo.setVisible(true);
    }//GEN-LAST:event_ModelosActionPerformed

    private void ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteActionPerformed
        // TODO add your handling code here:
        telaCliente telaCliente = new telaCliente();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_ClienteActionPerformed

public static void main(String[] args) {
    // Exibe a tela principal
    java.awt.EventQueue.invokeLater(() -> {
        new TelaInicial().setVisible(true);
    });
}
  /**
   * @param args the command line arguments
   */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Acessorio;
    private javax.swing.JButton Cliente;
    private javax.swing.JButton Marcas;
    private javax.swing.JButton Modelos;
    private javax.swing.JButton Posse;
    private javax.swing.JButton Veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
