
package visao;

import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import modelo.Aluno;

public class TelaIncluir extends javax.swing.JDialog {

    public TelaIncluir(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        aplicarMascaraMatricula();
        
        jComboBox_turno.setModel(new javax.swing.DefaultComboBoxModel(TURNO.values()));
    }
    public enum TURNO {
    MATUTINO,
    VESPERTINO,
    NOTURNO,
    }
    private boolean verificador = false;
    
    private void aplicarMascaraMatricula() {
    try {
        MaskFormatter formatter = new MaskFormatter("####.#.###.####");
        formatter.setPlaceholderCharacter('_');
        formatter.install(formattedTextFieldMatricula);
        formattedTextFieldMatricula.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                formattedTextFieldMatricula.setCaretPosition(0); 
            }
        });
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao aplicar a máscara na matrícula: " + e.getMessage());
    }
}
    
    public Aluno exportarDadosCadastro (Aluno alunoNov) throws Exception{
         try {
       if(verificador == true){
        alunoNov = new Aluno(formattedTextFieldMatricula.getText().toUpperCase(), jTextField_nome.getText().toUpperCase(), jComboBox_turno.getSelectedItem().toString(), Integer.parseInt(jTextField_periodo.getText()), jTextField_enfase.getText().toUpperCase(), jTextField_curso.getText().toUpperCase());
       }
       else{
           alunoNov = null;
       }
       
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage() + "exportar Dados cadastros\n");
        }
            return alunoNov;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jTextField_periodo = new javax.swing.JTextField();
        jTextField_enfase = new javax.swing.JTextField();
        jTextField_curso = new javax.swing.JTextField();
        jComboBox_turno = new javax.swing.JComboBox<>();
        jButton_incluir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        formattedTextFieldMatricula = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CADASTRO_ALUNOS");
        setPreferredSize(new java.awt.Dimension(500, 330));
        setResizable(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("MATRICULA:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NOME:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("TURNO:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("PERIODO:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("ENFASE:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("CURSO:");

        jTextField_nome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField_periodo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTextField_periodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_periodoActionPerformed(evt);
            }
        });
        jTextField_periodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_periodoKeyTyped(evt);
            }
        });

        jTextField_enfase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jTextField_curso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jComboBox_turno.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox_turno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MATUTINO", "VESPERTINO", "NOTURNO" }));
        jComboBox_turno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_turnoActionPerformed(evt);
            }
        });

        jButton_incluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_incluir.setText("INCLUIR");
        jButton_incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_incluirActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel8.setText("Incluir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton_incluir))
                            .addComponent(jTextField_nome)
                            .addComponent(formattedTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_periodo)
                            .addComponent(jTextField_enfase, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_curso, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(formattedTextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_enfase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_curso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox_turno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton_incluir))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_incluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_incluirActionPerformed
        // TODO add your handling code here:
        try {
            //verificacao de vazio
            if(formattedTextFieldMatricula.getText().isEmpty()) throw  new Exception("Matricula nao pode estar vazia\n");
            if(jTextField_periodo.getText().isEmpty()) throw  new Exception("periodo nao pode estar vazia\n");
            if(jTextField_curso.getText().isEmpty()) throw  new Exception("curso nao pode estar vazia\n");
            if(jTextField_nome.getText().isEmpty()) throw  new Exception("nome nao pode estar vazia\n");
            if(jTextField_enfase.getText().isEmpty()) throw  new Exception("enfase nao pode estar vazia\n");
            
            //outras verificacoes
            if(!jTextField_periodo.getText().matches("^[0-9]+$"))throw  new Exception ("o camp periodo somente aceita numeros\n");
            if(formattedTextFieldMatricula.getText().length() != 15)throw new Exception("formato de inserção de matricula errado, ");
            
            //formatarMatricula(jTextField_matricula.getText());
            verificador = true;
            this.dispose();
        } catch (Exception erro) {
        JOptionPane.showMessageDialog(this, erro.getMessage() + "Tela Cadastro\n");
        }
    }//GEN-LAST:event_jButton_incluirActionPerformed

    private void jTextField_periodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_periodoActionPerformed
        // TODO add your handling code here:;
    }//GEN-LAST:event_jTextField_periodoActionPerformed
    
    private void jTextField_periodoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_periodoKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume(); // Desfaz a tecla pressionada se não for um número
        }
    }//GEN-LAST:event_jTextField_periodoKeyTyped

    private void jComboBox_turnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_turnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_turnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaIncluir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaIncluir dialog = new TelaIncluir(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField formattedTextFieldMatricula;
    private javax.swing.JButton jButton_incluir;
    private javax.swing.JComboBox<String> jComboBox_turno;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField_curso;
    private javax.swing.JTextField jTextField_enfase;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_periodo;
    // End of variables declaration//GEN-END:variables
}
