/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import estrutura.ConjuntoAlunos;

public class TelaExcluir extends javax.swing.JFrame {

    private ConjuntoAlunos conjuntoAlunos;
    private TelaInicio telaInicio; 

    public TelaExcluir(ConjuntoAlunos conjuntoAlunos, TelaInicio telaPrincipal) {
    this.conjuntoAlunos = conjuntoAlunos;
    this.telaInicio = telaInicio;
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);   
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        excluirbox = new javax.swing.JComboBox<>();
        excluirbt = new javax.swing.JButton();
        excluir = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 210));
        setResizable(false);

        excluirbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Matricula" }));
        excluirbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirboxActionPerformed(evt);
            }
        });

        excluirbt.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        excluirbt.setText("Excluir");
        excluirbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirbtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("Excluir");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("EXCLUIR POR:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("INFORME O NOME/MATRICULA:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                        .addComponent(excluirbt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(excluirbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(excluirbt))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluirbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(excluir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirbtActionPerformed
        try {
        System.out.println("Alunos atuais: " + conjuntoAlunos.listar("crescente_nome"));
        
        if (conjuntoAlunos == null || conjuntoAlunos.listar("crescente_nome").isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nenhum aluno cadastrado.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String criterio = excluirbox.getSelectedItem().toString();
        String valor = excluir.getText().trim();
        
        if (valor.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo de exclusão.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }

        boolean excluido = false;

        if ("Matricula".equalsIgnoreCase(criterio)) {
            String numeroMatricula = valor.replaceAll("[^0-9]", "");
            excluido = conjuntoAlunos.excluirPorMatricula(numeroMatricula);
        } else if ("Nome".equalsIgnoreCase(criterio)) {
            excluido = conjuntoAlunos.excluirPorNome(valor);
        }

        if (excluido) {
            JOptionPane.showMessageDialog(this, "Aluno excluído com sucesso! Resliste a lista Principal para atualizala", "Sucesso",JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Aluno não encontrado!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Erro ao excluir: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_excluirbtActionPerformed

    private void excluirboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirboxActionPerformed
      try {
            String tipoBusca = excluirbox.getSelectedItem().toString();
            
            if (tipoBusca.equals("Matricula")) {
                MaskFormatter matriculaFormatter = new MaskFormatter("####.#.###.####");
                matriculaFormatter.setValidCharacters("0123456789");
                excluir.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(matriculaFormatter));
                excluir.setText("");
                excluir.setEditable(true);
                excluir.setCaretPosition(0);
                
                excluir.addFocusListener(new java.awt.event.FocusAdapter() {
                    @Override
                    public void focusGained(java.awt.event.FocusEvent evt) {
                        excluir.setCaretPosition(0); 
                    }
                });
            } else {
                excluir.setFormatterFactory(null);
                excluir.setText("");
                excluir.setEditable(true);
                excluir.setCaretPosition(0);
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(this, "Erro ao aplicar a máscara: " + erro.getMessage());
        }
    }//GEN-LAST:event_excluirboxActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField excluir;
    private javax.swing.JComboBox<String> excluirbox;
    private javax.swing.JButton excluirbt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
